import type { NextPage, GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import styles from '../styles/Home.module.css'
import { sanityClient, urlFor } from '../lib/sanity'

const projectsQuery = `*[_type == "project"]{
  _id,
  name,
  slug,
  mainImage,
}`;

const Home: NextPage = ({ projects } : InferGetStaticPropsType<typeof getStaticProps>) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Alexandre Neves</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to my portfolio</h1>

      <ul className="projects-list">
        { projects?.length > 0  && projects.map((project: any) => (
          <li key={ project._id } className="project-card">
            <Link href="/">
            <a>
              <img src={urlFor(project.mainImage).url()}/>
              <span>{ project.name }</span>
            </a>
            </Link>
          </li>
        ))}
      </ul>

    </div>
  )
  
}

export default Home;

export const getStaticProps : GetStaticProps = async () =>{

  const projects = await sanityClient.fetch(projectsQuery);
  return { props: { projects } };

}
